name: Test and Release

on:
  push:
    branches:
      - main
      - dev
      - 'release/v*'
  pull_request:
    branches:
      - main
      - dev
      - 'release/**'
      
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/v'))      
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.0'
          cache: true 

      - name: Run
        run: go test -v ./...

  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/v'))

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: false

      - name: Install Lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5

      - name: Run
        run: $(go env GOPATH)/bin/golangci-lint run --config=.golangci.yml

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: startsWith(github.ref, 'refs/heads/release/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Extract Tag Name
        id: extract_tag
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/release/}"
          TAG_NAME=$(echo "$BRANCH_NAME" | sed 's/-/\./g')
          echo "tag=$TAG_NAME" >> "$GITHUB_OUTPUT"

      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.extract_tag.outputs.tag }}
          git push origin ${{ steps.extract_tag.outputs.tag }}
          
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.extract_tag.outputs.tag }}
          name: "Release ${{ steps.extract_tag.outputs.tag }}"
          body: "Release automatically created from branch ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}